Coords after
marrink-lab/vermouth-martinize pull request #391
Opened 2021-11-17 12:47 UTC by fgrunewald

This is essentially an updated version of the coordinate builder but after the fact. This fixes mutations and everything where at the CG level coordinates are missing. This could also fix modifications like phosphorylation that are not actually present in the mapped pdb. Currently missing is a good routine for rebuilding VS. Luckily there is a very well tested routine in polyply. For now it only rebuilds VSN but that's good enough for proteins in Martini3 our main target. 

@pckroon 
Should we move the vs_builder from polyply to here eventually?

@Tsjerk 
As we discussed can you update the doc-strings with a little more information regarding how the coordinates are built and what quality checks are done. Also we'll need some tests here. Perhaps @pckroon can help with those as well a little. 

@paulocts 
You can use this branch for checking some examples, if you like.

2021-11-17 15:48 UTC, pckroon requested changes
I reviewed most of this code before, and I still don't like it very much. If this is merged as-is it'll incur a massive maintenance debt. If it breaks I'll have no idea where to look for the issue. The lack of comments and docstrings (the ones that are there are insufficient) acerbates the issue. Coupled to the absence of test this is time-bomb.
I assume I shouldn't get my hopes up regarding the missing tests, failing pylint, and docs?

I would very much welcome the VS routines from polyply here (make sure you can add the required citations, etc), but it will depend a little bit on the dependencies. Martinize2 only has a soft dependency on scipy, and making that a hard dependency needs to be a conscious decision.

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +    anchors = []
start with anchors as a set and add to that, rather first building a list and turning it to a set in the end

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +def triple_cone(n=24, distance=0.125, angle=109.4):
I think we briefly discussed this earlier, but there's no easy way of generalizing the double/triple/quadrupal cone constructions right? Even as a recursive function?

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +            if v != {}
```suggestion
            if not v
```
?

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +          based on R or S chirality.
```suggestion
    TODO: This function should probably be able to determine
          the weights of the substituents to allow placement
          based on R or S chirality.
```

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +            if v != {}
```suggestion
            if not v
```

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +        for i, (a, b) in enumerate(zip(self.anchors, self.bases)):
```suggestion
        for idx, (anchor, base) in enumerate(zip(self.anchors, self.bases)):
```
It costs nothing to expand these variable names, and it makes the code *so much* clearer...

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +                return [self]
Deduplicate this with the other branches

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +                    #return out
This is missing a "but". Why isn't it used?

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +        Process a single molecule. Must be implemented by subclasses.
This is not the docstring I am looking for. Move along.

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +        Process `system`.
This is not the docstring you are looking for.

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +            # Segment: subgraphs of limbs sharing anchors and bases
Some of these comments should be moved to the class

2021-11-17 15:48 UTC, pckroon commented on vermouth/processors/generate_coordinates.py
> +                s = segments.pop(0)
Nit: Not ideal to be popping from the left all the time. Is it possible to reverse sort the limbs above, and pop from the right here?

2022-07-15 15:16 UTC, fgrunewald commented
will take a second look at this in a clean PR that's not based on some other branches.

2022-07-15 15:16 UTC, closed without merging