keep resids of proteins if different or chains different
marrink-lab/vermouth-martinize pull request #399
Opened 2022-01-03 16:42 UTC by fgrunewald

This is a draft fix for issue #366 . Basically if the -protres flag is given the merge molecule will only compute a residue offset if any of the resids overlap and any of the chain identifiers overlap. In this way you just keep residue offsets in the same chain if there is no overlap and you also keep resids of different chains in the same molecule. This is the expected behavior for most PDBs and proteins.

Code wise this branch needs some improvements. But I think it makes sense to have a flag with merge molecule that dictates protein behaviour, because it is quite specific to proteins. Also I was thinking to API wise if it would make sense to maybe have generic criteria for how to merge molecules.

2022-02-04 10:28 UTC, pckroon requested changes
Overall looks quite good, but I have a few minor concerns on design. Also, tests and docstrings are missing (but this is still a draft, so fine for now).
The bigger discussion is what attributes we want to use to identify a residue (monomeric repeat unit). Chain + resname + resid sounds reasonable, but then we miss the case where there are no chain IDs, but there is a TER record between two chains. We can consider "fixing" the chain IDs in cases like that, or add a molecule_idx as identifier.

2022-02-04 10:28 UTC, pckroon commented on bin/martinize2
> +                                 " or resids when merging and preserve them if they are")
Help is missing an 'else'. I like the functionality, but I don't like the name of the flag. Can we think of something better?

2022-02-04 10:28 UTC, pckroon commented on vermouth/molecule.py
> +    def merge_molecule(self, molecule, offset_handling='simple'):
New argument missing in docstring, and the CLI option does store_true, but this string implies we'll support multiple strategies, which will cause a change in CLI API at a later point. I'd suggest changing the CLI option to take a string with a sane default

2022-02-04 10:28 UTC, pckroon commented on vermouth/molecule.py
> +        # between the two merging molecules. If chains are all different, resids
This is also a valid approach for DNA and arbitrary linear polymers, no? Anything for which a sane chain can be identified

2022-02-04 10:28 UTC, pckroon commented on vermouth/molecule.py
> +            # all chains are the same
/some/ chains are the same

2022-02-04 10:28 UTC, pckroon commented on vermouth/molecule.py
> +                    last_node_idx = max(self)
Add comment here on what this if branch will do (and why)

2022-02-04 10:28 UTC, pckroon commented on vermouth/molecule.py
> +                    last_node_idx = max(self)
Similar comment here

2022-02-04 10:28 UTC, pckroon commented on vermouth/molecule.py
> +            else:
And also here

2022-02-04 10:28 UTC, pckroon commented on vermouth/molecule.py
> +                    last_node_idx = max(self)
You need a last_node_idx for all cases, so move it up

2022-02-04 10:28 UTC, pckroon commented on vermouth/processors/merge_chains.py
> +def merge_chains(system, chains, offset_handling='simple'):
Missing in docstring

2022-07-14 12:00 UTC, fgrunewald commented
a better PR is on the way

2022-07-14 12:00 UTC, closed without merging