Make martinize2 accessible in python (see Issue #360)
marrink-lab/vermouth-martinize pull request #405
Opened 2022-02-25 20:53 UTC by OLaprevote

2022-02-28 13:13 UTC, pckroon requested changes
This is great! Many many thanks :D

While you were working on this I guess the API of the deferred file writer changed. It no longer exposes an `open`, but rather `deferred_open`. This is also what causes the test failures. 
I like how you formatted the docstring for the `martinize2` function, but I'm not sure what sphinx will think of it. I guess we'll find out. I can deal with it if sphinx doesn't like it.
Beside that a final request: currently there is a lot of duplication in the docstring (and signature) of martinize2 and the CLI. Could you open an issue to generate the signature and docstring from an argparse object? It's out of scope for this PR though.

Again, looks great! And thanks again

2022-02-28 13:13 UTC, pckroon commented on vermouth/martinize2.py
> +        ...     Path(vermouth.DATA_PATH) / 'force_fields')
I wouldn't linewrap this. If it's a little bit too long it's not a problem

2022-02-28 13:13 UTC, pckroon commented on vermouth/martinize2.py
> +        processors.Quoter().run_system(system)
Could you add a newline at the end?

2022-03-01 21:55 UTC, OLaprevote commented
Changes done :)
Yes, I thought so for Sphinx. I'm curious too, as you mentioned in a worst case scenario it's just removing a few lines.
Yup, the duplicated docstring is a pain. Looking into the problem right now: I have some ideas on how to proceed.

2022-03-02 10:51 UTC, pckroon commented
Thanks :)
There's something going wrong with passing filenames, and there's also something fishy with the docs that I can't reproduce locally... I'll see what's going on there.

> Yup, the duplicated docstring is a pain. Looking into the problem right now: I have some ideas on how to proceed.

I was thinking of the inspect module. That has the functionality to create/change signatures and docstrings on the fly. And the argparse object should have all the required info to fill the blanks. But like I said, it's out of scope for this PR. Could be a nice second one though ;)

> One thing: I left the `__init__.py` untouched. That means currently if anyone wants to use the python function they have to write from `vermouth.martinize2 import martinize2` (or `import vermouth.martinize2`). Would you rather have it more direct?

I think this is fine for now. We can always add it to the `__init__.py` at a later point.

2022-03-02 12:50 UTC, pckroon commented
Ok, small issue. The docstring style you use requires sphinx > 3.1.2. If I update my sphinx to the latest (4.4.0) I get about a million warnings. I'll open a separate PR to fix those, and then I think I'll come back here...

2022-03-24 14:25 UTC, pckroon commented
I'm going to try closing and reopening this PR to get the CI to run. Hopefully.

2022-03-25 17:49 UTC, OLaprevote commented
I've found a few mistakes in my docstrings as well while getting the automated documentation to work, e.g. missing colons. That may be one of the reason it doesn't pass the test. The corrections on the docstring and the automated documentation are right now one and only commit on my local computer: as soon as I have a bit of time I split them and push only the docstring changes.

2022-03-28 10:49 UTC, pckroon commented
Ok great :)
I'll patiently wait for those commits then!

2023-03-25 10:18 UTC, closed without merging