Fix/424
marrink-lab/vermouth-martinize pull request #440
Opened 2022-07-01 14:50 UTC by pckroon

Fix #439 
Note that the tests currently fail, since the behaviour of the parser regarding the replace attribute has changed. The pytest traceback is not pretty, but instead of using the "new" atomnames (after modification) we'd need to use the "old" ones. An example of this comes from one of the test forcefields (vermouth/tests/data/force_fields) pepplane. Instead of:
```
[ modification ]
[ from ]
universal-test
[ to ]
pepplane
[ from blocks ]
C-ter
[ to blocks ]
C-ter
[ mapping ]
C   BB
O1  BB
O2  BB
[ reference atoms ]
BB C
```
we'd have to write
```
[ modification ]
[ from ]
universal-test
[ to ]
pepplane
[ from blocks ]
C-ter
[ to blocks ]
C-ter
[ mapping ]
C   BB
O  BB
OXT  BB
[ reference atoms ]
BB C
```
See also: `vermouth/tests/data/force_fields/universal-test/modifications.ff` and `vermouth/tests/data/mappings/universal-test/pepplane/modifications.mapping`.
@fgrunewald Is this change in behaviour acceptable/desirable? Or should it be augmented so you could use either name?

2022-07-04 08:56 UTC, fgrunewald commented
@pckroon I don't quite get why there was a replace attribute in the mapping file in the first place?

2022-07-04 14:20 UTC, pckroon commented
I'm not completely sure what you mean.
To build/construct the Mapping object you need to mention atoms by their unique atom names. However, the discussion here is because we have multiple possible sources of atom names:
1. PDB (Terrible idea)
2. Block (Doesn't include atoms added by modifications)
3. Modification before replacement (Contains a mix of canonical and non-canonical atom names, such as O and OXT vs O1 and O2)
4. Modification after replacement (May contain duplicate atom names iff atoms get removed)

Before this PR (i.e. in master) the behaviour is to use source 4 as truth, but that causes issues. So the question for the discussion is whether just using source 3 is acceptable, or whether we should do something more intelligent, such as "try 4, but if that doesn't work fall back to 3"

2022-07-04 14:31 UTC, fgrunewald commented
what I try to say is that in the ideal word the name in the PDB file would be the same as the name in the modifications directive '[atoms]' and the same in the mapping file (i.e. source 3). That makes intuitively for me the most sense. So if 3 works would even be an improvement.

2022-07-04 14:37 UTC, fgrunewald commented
you miss my point but that's fine. For me 3 makes intuitively sense.

2022-07-04 14:38 UTC, pckroon commented
> you miss my point but that's fine. For me 3 makes intuitively sense.

Completely. Could you try wording it again? I do appreciate your take on this...

2022-07-06 09:36 UTC, fgrunewald requested changes
Overall looks good to me. However, the old-atomname matcher function could use a second look. Is it really a good strategy to copy the complete node-dict and feed that to node-matcher? If yes then that's ok for me. 

Also all C/N-ter files in martini need updating now or am I mistaken?

2022-07-06 12:07 UTC, pckroon commented
> Overall looks good to me. However, the old-atomname matcher function could use a second look. Is it really a good strategy to copy the complete node-dict and feed that to node-matcher? If yes then that's ok for me.

Does it hurt though? Either way, separate PR. I didn't change it for this one.

2022-07-06 12:07 UTC, pckroon commented on vermouth/processors/do_mapping.py
> +    is_equal = _old_atomname_match(mol_node, map_node)
No it's much older. It comes from 8928f9316ff38a343905121bd3fc47bf65f8ad58, 4 years ago.

2022-07-06 12:10 UTC, pckroon commented
> Also all C/N-ter files in martini need updating now or am I mistaken?

Don't think so. The universal ff uses O/OXT and NH/NH2/NH3, so it's a non-issue.

2022-07-06 13:47 UTC, fgrunewald approved these changes

2022-07-07 11:13 UTC, merged