merge eunit and region flag
marrink-lab/vermouth-martinize pull request #465
Opened 2022-09-07 12:39 UTC by fgrunewald

This fixes #459 at least partially. As stated in the issue there is still some ambiguity as to what exactly should happen if a resid region is defined for a molecule with more than one chain and same resids per chain

2022-09-09 09:25 UTC, pckroon requested changes
Few typos, nothing major.

I am starting to have doubt to what's the desired behaviour though. Is it not desirable to be able to combine `-eunit chain` with `-region 200:400`? The behaviour would be that EB only get made where both conditions are true.
Also, CLI nitpick, when I provide an `-eunit` I'd argue the `-elastic` is implied, but that can be shelved for a while.

2022-09-09 09:25 UTC, pckroon commented on bin/martinize2
> +                                'specified region defined by resids, with follwing'
```suggestion
                                'specified region defined by resids, with following'
```

2022-09-09 09:25 UTC, pckroon commented on vermouth/tests/data/integration_tests/tier-1/EN_chain/README
> +# Human Insluin HOMRO dimer
```suggestion
# Human Insulin HOMRO dimer
```

2022-09-09 09:25 UTC, pckroon commented on vermouth/tests/data/integration_tests/tier-1/EN_chain/README
> +# 2 chains which are connecte by disulphide bridge
```suggestion
# 2 chains which are connected by disulphide bridge
```

2022-09-09 09:25 UTC, pckroon commented on vermouth/tests/data/integration_tests/tier-1/EN_region/README
> +# Human Insluin HOMRO dimer
```suggestion
# Human Insulin HOMRO dimer
```

2022-09-09 09:25 UTC, pckroon commented on vermouth/tests/data/integration_tests/tier-1/EN_region/README
> +# 2 chains which are connecte by disulphide bridge
```suggestion
# 2 chains which are connected by disulphide bridge
```

2022-09-10 21:18 UTC, fgrunewald commented
As far as the behaviour goes the `eunit=chain` is really just an edgy edge case. It only comes to be important when two chains, which are labelled as such are connected by a disulphide bridge. Any thing else will end as two separate molecules or one molecule. Thus I think it is fine having the eunit flag being either all, molecule, chain, or residrange.

2022-09-12 13:39 UTC, pckroon commented
Then maybe chain + region was a poorly chosen example. 
How about molecule + region? You may want an elastic network only within a molecule/chain, but only between resids 200-400. So if you have 2 homodimers that are close together you only want EN between resid 200-400, but not between the two dimers. I think that's not possible with the current CLI suggestion

2022-09-15 11:52 UTC, fgrunewald commented
@Tsjerk any thoughts on this

2022-10-03 09:40 UTC, pckroon approved these changes
Ok, that works for me. I'll open a fresh issue.

2022-10-03 10:19 UTC, merged