Sort nodes to group residues
marrink-lab/vermouth-martinize pull request #469
Opened 2022-10-03 13:02 UTC by pckroon

Adds a processor to assign consecutive atomids to molecules, sorted by chain and resid. That way residues will be grouped together in the resulting PDB and ITP file(s).

@fgrunewald Is this more or less as you intended? If yes I'll add some tests.

2022-10-07 10:55 UTC, fgrunewald commented on vermouth/processors/sort_nodes.py
> +                 target_attr='atomid'):
Docstring?

2022-10-07 11:00 UTC, fgrunewald requested changes
If I understand correctly it sorts by four factors and the target attribute is the one that is overwritten? This Processor could use some commenting in that regard. Otherwise looks good to me. I would, however, suggest to at least in the doc-string define types that are eligible for group by. It must be a sort able node attribute right like a graph would not work?

2022-10-10 09:45 UTC, pckroon commented
It was my plan to write proper docstrings and tests, but I wanted to make sure this is roughly the desired behaviour. I'll push the commits hopefully soon.

2023-02-06 13:32 UTC, pckroon commented
`E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dssp/dssp_3.0.0-3build1_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (20.106.104.242), connection timed out` *sigh*

2023-02-06 15:52 UTC, pckroon commented
Tests are working again.

2023-02-06 15:53 UTC, fgrunewald approved these changes
Looks good to me.

2023-02-06 15:54 UTC, fgrunewald approved these changes

2023-02-06 16:07 UTC, fgrunewald commented
@pckroon feel free to merge

2023-02-07 12:40 UTC, pckroon commented on vermouth/processors/sort_molecule_atoms.py
> +            LOGGER.warning("{} is not in {}. Atom sorting may be unstable.",
Unstable has a specific meaning in the context of sorting. Consider the following:
`[B1, A2, C1, A1, C3]`. We're going to sort these by letter (numbers are to distinguish the objects with the same letter). A stable sorting will produce `[A2, A1, B1, C1, C3]`, while an unstable sorting *may* swap A2 and A1 and C1 and C3. Stable sorting means that objects which compare as equal remain in the same relative order.

2023-02-07 12:40 UTC, merged