-el fix
marrink-lab/vermouth-martinize pull request #559
Opened 2023-10-31 16:38 UTC by csbrasnett

Currently, if elastic network rubber bands are applied and are 1) below the cutoff for -el and 2) not otherwise eliminated by the -ermd threshold for the force field, they are kept in. Ie. the -el cutoff is not actually currently applied. This PR applies the cutoff.

2023-11-01 11:51 UTC, fgrunewald commented
@csbrasnett do you dare to add a test for this behaviour? Editing 'tests/test_apply_rubber_bands' would be the place. Probably would make sense to add a new test for the compute_force_constants function. To get started you can ask chatGPT to write a test for example.

2023-11-01 13:18 UTC, csbrasnett commented
@fgrunewald I was worried you'd ask... Have had a go now, that'll cover the testing of the different bounds. I haven't added anything to test the decay factors/powers because that gets in to testing floats and I didn't want to get in to that.

2023-11-01 13:42 UTC, fgrunewald requested changes
For extendability purposes I suggest to use np.allclose and then you could also add a test for the decay factor but totally optional here.

2023-11-01 13:42 UTC, fgrunewald commented on vermouth/tests/test_apply_rubber_band.py
> +    assert result.all() == expected_output.all()
If you want to test floats you can use `np.allclose(array1, array2)` together with setting the absolute tolerance for the float. Or Peter seems to prefer the pytest build in using pytest.approx.

2023-11-01 14:46 UTC, fgrunewald approved these changes

2023-11-02 12:14 UTC, pckroon commented
I'm not sure the behaviour you propose here is desired actually. The semantics between upper and lower bounds are annoyingly different in this context. The code you propose to change has been there since #54, the initial implementation for the EN.

If this change goes through we will produce a *different* elastic network than martinize1

2023-11-02 12:18 UTC, fgrunewald commented
@csbrasnett did you compare this to martinize1? Also @pckroon I don't really care if we diverge here. The implementation in martinize1 seems just incorrect or am I missing something?

2023-11-02 12:31 UTC, csbrasnett commented
I haven't checked against martinize1, I can try and find time today. 

But actually @pckroon is correct in that if the distance is < lower then it needs to just be set as the constant, rather than being deleted as this currently behaves. Which still wasn't happening before - eg. if you applied a decay and a lower cutoff, then the forces below the cutoff would be larger than the given constant. But that's easy enough to change. I can fix these and check against martinize1 if we agree that's the expected behaviour?

2023-11-02 13:52 UTC, csbrasnett commented
Right, so this would change the behaviour against martinize1, which currently reproduces what the main branch does. However, I 1) cannot find where the concept of a _lower_ cutoff has emerged from, as in both the papers and the citation trail that follows, only the _upper_ cutoff is ever discussed.

That said, I still think that the expected behaviour is currently wrong based on the descriptions. This PR now actually only fixes the side case where decays are used. In the fig here, where ea = ep = 0, the force is constant below el for both old and new. But with decays (and with line 99 now reading `constants[distances < lower_bound] = base_constant` as it should) the force below the el is correctly set to the given force constant.


![fig](https://github.com/marrink-lab/vermouth-martinize/assets/35073246/6689d7d9-98ac-4d62-a627-1625399122ef)

2023-11-02 14:26 UTC, pckroon submitted a review, later dismissed
Excellent. Thanks for digging up the details!

2023-11-02 14:35 UTC, csbrasnett commented
Thanks! nb don't merge yet, need to add the final condition, which isn't as trivial as I thought it'd be.

2023-11-03 08:52 UTC, fgrunewald requested changes
@csbrasnett let us know once you're done.

2023-11-03 10:44 UTC, csbrasnett commented
@fgrunewald now corrected. Based on the discussion and graph above, I realised the second condition wasn't actually necessary, because the deviation is constant > base_constant for distance < el, so it's simple enough to set anything larger as the base_constant.

2023-11-03 14:47 UTC, fgrunewald submitted a review, later dismissed

2023-11-06 12:31 UTC, pckroon approved these changes
I'd be very happy if you could expand the docstring of compute_force_constants now that you know exactly what it does and is supposed to do.
LGTM otherwise, nice work :)

2023-11-06 13:41 UTC, pckroon approved these changes

2023-11-13 12:36 UTC, merged