Multiple mutate fixes
marrink-lab/vermouth-martinize pull request #565
Opened 2023-12-14 13:07 UTC by csbrasnett

re-addresses #553 in the case that mutations are given across multiple chains. This PR makes sure that in the case that multiple chains are targeted, the check for the target residue existing is not present across all chains. So warnings aren't raised when the 'missing' residue is encountered.

2023-12-14 13:58 UTC, pckroon requested changes
Thanks for picking up this issue.
I'm not very happy with how much code duplication this solution produces though...
Maybe you can abstract the duplicated functionality in a separate function (maybe that would return the affected nodes?)? As alternative, make the resspecs-to-find attributes of the AnnotateMutMod Processor, and make sure you find each at least once when running run_system.
```py
def run_system(system):
    self.resspec_counts = ...
    # Modify run_molecule to increment the resspec_counter(s)
    super().run_system()
    if any(self.resspec_counts == 0): warn
```

2023-12-14 13:58 UTC, pckroon commented on vermouth/processors/annotate_mut_mod.py
> +                                   ''.format(_format_resname(resspec)))
```suggestion
                if not mod_found:
                    LOGGER.warning('Residue specified by "{}" for mutation "{}" not found. ', _format_resname(resspec), mod)
```

2023-12-14 13:58 UTC, pckroon commented on vermouth/processors/annotate_mut_mod.py
> +            elif resspec.get(chain) == None:
```suggestion
            elif resspec.get(chain) is None:
```

2023-12-14 13:58 UTC, pckroon commented on vermouth/processors/annotate_mut_mod.py
> +            # If instead we're targeting all residues in the chain
```suggestion
            # If instead we're targeting residues in any chain
```

2023-12-14 13:58 UTC, pckroon commented on vermouth/processors/annotate_mut_mod.py
> +    def run_system(self, system):
```suggestion
        return molecule
    
    def run_system(self, system):
```

2023-12-14 13:58 UTC, pckroon commented on vermouth/processors/annotate_mut_mod.py
> +        system.molecules = mols
What does this add over `super().run_system()`?

2024-04-05 14:30 UTC, pckroon requested changes
Nice bit of cleanup :) I do think I spotted a (small) mistake though, and there are some small comments left over from before.
I forgot why the different behaviour for whether a chain is specified or not?

2024-04-05 14:30 UTC, pckroon commented on vermouth/processors/annotate_mut_mod.py
> +            if mod != 'none' and mod not in library:
```suggestion
            if mod != 'none' and mod not in library[key]:
```
?

2024-04-05 14:30 UTC, pckroon commented on vermouth/processors/annotate_mut_mod.py
> +def _resiter(mod, residue_graph, resspec, library, key, molecule):
Needs a docstring, especially with the number of arguments it takes

2024-04-08 09:51 UTC, pckroon commented
Updating the codecov action seems to have fixed the failing test thingie

2024-04-08 11:22 UTC, csbrasnett commented
just to check, are you expecting any more changes from me?

2024-04-08 12:21 UTC, pckroon reviewed
I think this still gives erroneous warnings for chemically disconnected things. For example, protein with 2 chains (A and B) which are not connected by a chemical bond (and are thus separate Molecules), combined with a valid resspec that defines a chain.

2024-04-08 13:09 UTC, pckroon requested changes
One more testcase: I think `{'resname': 'GLY', 'resid: 1'}` will not print a warning even if it doesn't match anything.
After that I'm happy :)

2024-04-08 14:00 UTC, csbrasnett commented
So, I think those tests do what you expect them to, but I'm not sure they should work, as they don't pick up on the error identification correctly? Eg, GLU4:GLY should mutate any GLU at resid 4 on every chain, but if resid 4 is not GLU then there should be a warning, and there currently isn't. I'll have a think about how to address this.

I'll also update the martinize2 help to add some more detail about what's possible with the mutate/modify flags?

2024-04-09 07:44 UTC, pckroon commented
>  Eg, GLU4:GLY should mutate any GLU at resid 4 on every chain, but if resid 4 is not GLU then there should be a warning, and there currently isn't.

Exactly :)
I think you'll need to adapt the run_system method to track whether at the end there are any resspecs that didn't match anything

> I'll also update the martinize2 help to add some more detail about what's possible with the mutate/modify flags?

This is always welcome. Documentation is not my strong suite

2024-04-09 08:04 UTC, pckroon commented
That warning works for single molecules, not the entire system, which is what's going wrong if you have a resspec that does not mention any chains but does not match anywhere

2024-04-09 08:30 UTC, csbrasnett commented
> That warning works for single molecules, not the entire system, which is what's going wrong if you have a resspec that does not mention any chains but does not match anywhere

I'm pretty sure that possibility's covered by this test though: 

```
[
    {'chain': 'A', 'resname': 'ALA', 'resid': 1},
    {'chain': 'A', 'resname': 'ALA', 'resid': 2},
    {'chain': 'A', 'resname': 'ALA', 'resid': 3},
    {'chain': 'B', 'resname': 'ALA', 'resid': 1},
    {'chain': 'B', 'resname': 'ALA', 'resid': 2},
    {'chain': 'B', 'resname': 'ALA', 'resid': 3}
],
[(0, 1), (1, 2), (3, 4), (4, 5)],
[({'resname': 'GLY', 'resid': 1}, 'ALA')],
True
```

ie. two molecules in the system, target any GLY with resid 1 (of which there are none), and expect a warning to be raised

2024-04-10 14:40 UTC, pckroon commented
Since the test was always running on a single Molecule (rather than a System of multiple molecules) it was hiding the issue I was trying to dig up.
The problem is that  if a resspec does not get applied to /all/ molecules, a warning gets issued, even if it applies to at least 1.

2024-04-11 11:09 UTC, csbrasnett commented
thanks for that additional test, I see what you mean now about what wasn't captured. Will fix in due course!

2024-04-11 15:05 UTC, pckroon commented on vermouth/tests/test_annotate_mut_mod.py
> +        False
This test should raise a warning, since there is no GLY in chain A?

2024-04-12 08:58 UTC, pckroon commented
No worries. I know how these things can happen.
My suggestion is to simplify the `annotate_modifications` function again, to simply apply yes or no depending on whether the resspec was matched anywhere. Being able to warn whether a modification applied to just one or all chains is nice to have, but not necessary.  The most relevant message is when a modification doesn't apply anywhere. I'll leave it up to you whether the more detailed message is worth the added complexity.

2024-04-22 11:09 UTC, pckroon requested changes

2024-04-23 08:48 UTC, pckroon requested changes
One last nitpick, LGTM otherwise!

2024-04-23 08:48 UTC, pckroon commented on vermouth/processors/annotate_mut_mod.py
> +def annotate_modifications(molecule, modifications, mutations, resspec_counts):
Final Nitpick, could you add the new argument to the docstring, and emphasize there that it is modified in place?

2024-04-23 13:00 UTC, pckroon approved these changes
Nice work! Thanks for following through and dealing with all the small nitpicks!

2024-04-23 13:00 UTC, merged