Idp go
marrink-lab/vermouth-martinize pull request #593
Opened 2024-04-29 08:14 UTC by csbrasnett

Adding -idp-tune to allow for addition of extra bonded potentials in IDRs

2024-05-01 13:48 UTC, pckroon requested changes
Some small code comments, and a conceptual suggestion.
You want to add some interactions to specific disordered regions of a protein, right? My suggestion would be to have a simple processor annotate nodes/residues that are in an IDR, and add the interactions using links

2024-05-01 13:48 UTC, pckroon commented on vermouth/processors/tune_idp_bonds.py
> +# Copyright 2018 University of Groningen
```suggestion
# Copyright 2024 University of Groningen
```

2024-05-01 13:48 UTC, pckroon commented on vermouth/processors/tune_idp_bonds.py
> +            res_graph = make_residue_graph(molecule)
```suggestion
        if hasattr(molecule, 'res_graph'):
            res_graph = molecule.res_graph
        else:
            res_graph = make_residue_graph(molecule)
            molecule.res_graph = res_graph
```
?

2024-05-01 13:48 UTC, pckroon commented on vermouth/processors/tune_idp_bonds.py
> +    def run_molecule(self, molecule):
Don't forget to attach the appropriate citation reference to the molecule

2024-05-01 13:48 UTC, pckroon commented on vermouth/processors/tune_idp_bonds.py
> +        for i in all_cross_pairs[::-1]:
```suggestion
        for i in reversed(all_cross_pairs):
```

2024-05-02 11:26 UTC, csbrasnett commented
This is a much nicer solution, thanks for suggesting!

2024-05-06 08:33 UTC, pckroon requested changes
Much cleaner! <3
Still a few small comments

2024-05-06 08:33 UTC, pckroon commented on bin/martinize2
> +            vermouth.IDRBonds(idr_regions = [(int(start), int(stop)) for start, stop in args.water_idrs]).run_system(system)
```suggestion
            vermouth.IDRBonds(idr_regions=[(int(start), int(stop)) for start, stop in args.water_idrs]).run_system(system)
```

2024-05-06 08:33 UTC, pckroon commented on bin/martinize2
> +            vermouth.DoLinks().run_system(system)
I don't think you actually want to run DoLinks a second time. Instead, move the IDRBonds annotator to just after the mapping

2024-05-06 08:33 UTC, pckroon commented on vermouth/processors/tune_idp_bonds.py
> +        if select_backbone(node):
I wouldn't tag just the  backbone (or SC1), but rather just all nodes with the appropriate resid

2024-05-06 08:33 UTC, pckroon commented on vermouth/processors/tune_idp_bonds.py
> +                order_disorder_seq.append("D")  # D for disordered
Why first build the list/string, and not just do `molecule.nodes[key]['is_idr'] = True` here?

2024-05-07 08:54 UTC, pckroon requested changes

2024-05-07 08:54 UTC, pckroon commented on bin/martinize2
> +def martinize(system, mappings, to_ff, delete_unknown=False, idrs=False, disordered_regions = []):
```suggestion
def martinize(system, mappings, to_ff, delete_unknown=False, idrs=False, disordered_regions=(,)):
```
As before, no mutable types as default arguments

2024-05-07 08:54 UTC, pckroon commented on bin/martinize2
> +    #         vermouth.DoLinks().run_system(system)
```suggestion
```

2024-05-07 08:54 UTC, pckroon commented on vermouth/processors/annotate_idrs.py
> +    """
Docstring is incomplete.
Also, is it worth making the attribute used an argument (with default "cgidr")?

2024-05-07 08:54 UTC, pckroon commented on vermouth/processors/annotate_idrs.py
> +    def __init__(self, idr_regions = None):
```suggestion
    def __init__(self, idr_regions=None):
```

2024-05-07 08:54 UTC, pckroon commented on vermouth/processors/annotate_idrs.py
> +        self.system = system
```suggestion
```
Why do you need this?

2024-05-22 09:30 UTC, csbrasnett commented
btw, in trying to write some tests to address the missing coverage I've found an error in the test here:

https://github.com/marrink-lab/vermouth-martinize/blob/e9bf1c928efde188d70f9d9c710032a8a2f81672/vermouth/tests/test_water_bias.py#L89-L98

in that the if statement is testing an atomtype against an atom index. Easy enough to fix, but it does now cause this test to fail once the the eps and sig assertions are actually reached! I'll fix here and you can have a look

2024-05-22 11:42 UTC, pckroon submitted a review, later dismissed
LGTM! Was there anything still missing in this PR?

2024-05-22 11:53 UTC, csbrasnett commented
Thanks! Making a test for the folded/disordered go bond removal, should be done soon!

2024-05-22 12:24 UTC, csbrasnett commented
you mean in addition to what I've done here now?

2024-05-22 12:31 UTC, pckroon commented
Yes :)

2024-05-22 14:17 UTC, csbrasnett commented
This is proving more difficult than anticipated... I'm guessing in general you have something in mind like this. Ie. you have two folded domains connected by some linker, and you want to 1) keep intra-domain go bonds, 2) remove domain-linker bonds, and 3) remove inter-domain bonds? I this should be possible but I need to make some big edits to the removal functionality 

![image](https://github.com/marrink-lab/vermouth-martinize/assets/35073246/48df44ee-68cd-420e-a198-98ed6b629ae3)

2024-05-22 14:20 UTC, pckroon commented
What I mean is that in `test_water_bias.py:test_cross_go_bond_removal` you either remove all or none. I'm not sure that's going to be the same case as you describe tbh

2024-05-22 14:39 UTC, csbrasnett commented
ok, I think that addresses your point?

2024-05-22 15:03 UTC, pckroon approved these changes
Yes, perfect

2024-05-22 15:05 UTC, merged